const PDFDocument = require("pdfkit");

/**
 * Service for generating PDF reports from analysis results
 */

/**
 * Generate a PDF report from analysis results
 * @param {Object} analysisResult - The complete analysis result
 * @param {Object} res - Express response object to stream to
 */
const generateReport = (analysisResult, res) => {
  // Create a new PDF document
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  // Set response headers for PDF download
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="LexiRisk_Report_${analysisResult.documentName}.pdf"`,
  );

  // Pipe the PDF to the response
  doc.pipe(res);

  // --- Header ---
  doc.fontSize(24).fillColor("#0F172A").text("LexiRisk", { align: "left" });
  doc
    .fontSize(12)
    .fillColor("#64748B")
    .text("Legal Document Risk Analysis Report", { align: "left" });
  doc.moveDown();
  doc
    .fontSize(10)
    .text(
      `Generated: ${new Date(analysisResult.processedAt).toLocaleString()}`,
      { align: "left" },
    );
  doc.moveDown(2);

  // --- Document Info ---
  doc.fontSize(18).fillColor("#0F172A").text("Document Information");
  doc.moveDown(0.5);
  doc.fontSize(11).fillColor("#334155");
  doc.text(`Document: ${analysisResult.documentName}`);
  doc.text(`Total Clauses: ${analysisResult.totalClauses}`);
  doc.moveDown(2);

  // --- Risk Score (Prominent) ---
  doc.fontSize(18).fillColor("#0F172A").text("Overall Risk Assessment");
  doc.moveDown(0.5);

  const riskColor =
    analysisResult.riskScore >= 70
      ? "#DC2626"
      : analysisResult.riskScore >= 40
        ? "#D97706"
        : "#059669";

  doc
    .fontSize(36)
    .fillColor(riskColor)
    .text(`${analysisResult.riskScore}/100`, { align: "center" });
  doc
    .fontSize(16)
    .fillColor(riskColor)
    .text(analysisResult.riskLabel, { align: "center" });
  doc.moveDown(2);

  // --- Extracted Entities ---
  if (analysisResult.entities) {
    doc.fontSize(18).fillColor("#0F172A").text("Extracted Information");
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor("#334155");

    Object.keys(analysisResult.entities).forEach((key) => {
      const entity = analysisResult.entities[key];
      if (entity.value) {
        const label = key
          .replace(/([A-Z])/g, " $1")
          .replace(/^./, (str) => str.toUpperCase());
        doc.text(
          `${label}: ${entity.value} (${entity.confidence}% confidence)`,
        );
      }
    });
    doc.moveDown(2);
  }

  // --- Top Risky Clauses ---
  const riskyClauses = analysisResult.clauses
    .filter((c) => c.riskLevel === "high")
    .slice(0, 3);

  if (riskyClauses.length > 0) {
    doc.addPage();
    doc.fontSize(18).fillColor("#0F172A").text("Top Risk Factors");
    doc.moveDown(1);

    riskyClauses.forEach((clause, index) => {
      doc
        .fontSize(12)
        .fillColor("#DC2626")
        .text(`${index + 1}. ${clause.clauseTitle}`);
      doc
        .fontSize(10)
        .fillColor("#334155")
        .text(clause.plainEnglishSummary || "No summary available", {
          width: 500,
        });
      doc.moveDown(1);
    });
  }

  // --- Full Clause Breakdown ---
  doc.addPage();
  doc.fontSize(18).fillColor("#0F172A").text("Complete Clause Analysis");
  doc.moveDown(1);

  analysisResult.clauses.forEach((clause, index) => {
    // Check if we need a new page
    if (doc.y > 650) {
      doc.addPage();
    }

    const riskColors = {
      high: "#DC2626",
      medium: "#D97706",
      low: "#059669",
      none: "#64748B",
    };

    doc
      .fontSize(12)
      .fillColor("#0F172A")
      .text(`${clause.clauseNumber}. ${clause.clauseTitle}`);
    doc
      .fontSize(10)
      .fillColor(riskColors[clause.riskLevel] || "#64748B")
      .text(
        `Risk: ${clause.riskLevel?.toUpperCase() || "NONE"} (Confidence: ${clause.confidenceScore || 0}%)`,
      );
    doc
      .fontSize(9)
      .fillColor("#475569")
      .text(clause.plainEnglishSummary || "No summary available", {
        width: 500,
      });
    doc.moveDown(1);
  });

  // --- Footer on last page ---
  doc
    .fontSize(8)
    .fillColor("#94A3B8")
    .text(
      "This report was generated by LexiRisk AI and should not replace professional legal advice.",
      50,
      doc.page.height - 50,
      { align: "center", width: doc.page.width - 100 },
    );

  // Finalize the PDF
  doc.end();
};

module.exports = {
  generateReport,
};
